#!/bin/bash

set -e
set -u


cat <<EOF
Name:
Dataset:
Authors:
PI: 
Description:
Scripts:
EOF

for i in "$@"
do
    echo "  -name: $i"
    echo "   desc:"
    echo "   md5sum: $(md5sum $i | cut -d ' ' -f 1)"
done

cat <<EOF
Outputs:
Server:
Notes:
EOF
